from django.conf.urls.defaults import *

urlpatterns = patterns('programas.views',
        (r'^$', 'lista'),
        (r'^exercicio1/$', 'exercicio1'),
        (r'^exercicio2/$', 'exercicio2'),
        (r'^exercicio3/$', 'exercicio3'),
        (r'^exercicio4/$', 'exercicio4'),
        (r'^exercicio5/$', 'exercicio5'),
        (r'^exercicio6/$', 'exercicio6'),
        (r'^exercicio7/$', 'exercicio7'),
        (r'^exercicio8/$', 'exercicio8'),
        (r'^exercicio9/$', 'exercicio9'),
        (r'^exercicio10/$', 'exercicio10'),
        (r'^exercicio11/$', 'exercicio11'),
        (r'^exercicio12/$', 'exercicio12'),
        (r'^exercicio13/$', 'exercicio13'),
        (r'^exercicio14/$', 'exercicio14'),
        (r'^exercicio15/$', 'exercicio15'),
        (r'^exercicio16/$', 'exercicio16'),
        (r'^exercicio17/$', 'exercicio17'),
        (r'^exercicio18/$', 'exercicio18'),
        (r'^exercicio19/$', 'exercicio19'),
    )

